DROP TABLE IF EXISTS INPUT_TEXT;
DROP TABLE IF EXISTS INPUT_USER;

CREATE TABLE INPUT_USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  USER_NAME VARCHAR(500)
);

CREATE TABLE INPUT_TEXT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  TEXT VARCHAR(500),
  USER_ID INT,
  CREATED_AT TIMESTAMP,

  CONSTRAINT FK_INPUT_TEXT_INPUT_USER FOREIGN KEY (USER_ID) REFERENCES INPUT_USER(ID)
);